name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *' # Ejecuta todos los días a medianoche
  workflow_dispatch:     # Permite ejecutarlo manualmente también

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-close: 7
          stale-issue-message: 'Este issue ha estado inactivo por 30 días. Se cerrará automáticamente en 7 días si no hay actividad.'
          close-issue-message: 'Este issue ha sido cerrado automáticamente por inactividad.'
          stale-pr-message: 'Este PR ha estado inactivo por 30 días. Se cerrará automáticamente en 7 días si no hay actividad.'
          close-pr-message: 'Este PR ha sido cerrado automáticamente por inactividad.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
